//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERMessage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class per_Borrow
    {
        public long per_Borrow_ID { get; set; }
        public Nullable<long> per_ID { get; set; }
        public Nullable<long> per_UserID { get; set; }
        public Nullable<int> per_Borrow_state { get; set; }
        public Nullable<System.DateTime> per_Borrow_date { get; set; }
        public Nullable<System.DateTime> per_Return_date { get; set; }
    
        public virtual per_Data per_Data { get; set; }
        public virtual per_User per_User { get; set; }
    }
}
