//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERMessage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class per_RoleRight
    {
        public long UPR_ID { get; set; }
        public Nullable<long> Role_ID { get; set; }
        public string RC_ID { get; set; }
    
        public virtual per_RightCode per_RightCode { get; set; }
        public virtual per_Role per_Role { get; set; }
    }
}
