//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERMessage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class per_Box
    {
        public long per_BoxID { get; set; }
        public string per_Box_Uniquce_ide { get; set; }
        public Nullable<long> per_P_ID { get; set; }
        public string per_ArchivesID { get; set; }
        public string per_Res_people { get; set; }
        public string per_description { get; set; }
    
        public virtual per_InfoData per_InfoData { get; set; }
    }
}
