//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERMessage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class per_Data
    {
        public per_Data()
        {
            this.per_Borrow = new HashSet<per_Borrow>();
        }
    
        public long per_ID { get; set; }
        public Nullable<long> per_P_ID { get; set; }
        public Nullable<long> per_UserID { get; set; }
        public Nullable<int> per_Cancel_state { get; set; }
        public Nullable<int> per_Approve_state { get; set; }
        public string per_Unapprove_cause { get; set; }
        public string per_Delete_cause { get; set; }
        public Nullable<System.DateTime> per_Delete_date { get; set; }
        public Nullable<long> per_Borrow_count { get; set; }
    
        public virtual ICollection<per_Borrow> per_Borrow { get; set; }
        public virtual per_InfoData per_InfoData { get; set; }
        public virtual per_User per_User { get; set; }
    }
}
