//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERMessage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class per_Log
    {
        public long per_LogID { get; set; }
        public Nullable<long> per_AdminID { get; set; }
        public Nullable<System.DateTime> per_AdminDate { get; set; }
        public string per_AdminDo { get; set; }
        public Nullable<long> per_DocumentID { get; set; }
    }
}
