//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERMessage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class per_RightCode
    {
        public per_RightCode()
        {
            this.per_RoleRight = new HashSet<per_RoleRight>();
        }
    
        public string RC_ID { get; set; }
        public string RC_ParentCode { get; set; }
        public string RC_Text { get; set; }
        public string RC_Url { get; set; }
        public string RC_Tip { get; set; }
    
        public virtual ICollection<per_RoleRight> per_RoleRight { get; set; }
    }
}
