//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERMessage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class per_InfoData
    {
        public per_InfoData()
        {
            this.per_Box = new HashSet<per_Box>();
            this.per_Data = new HashSet<per_Data>();
            this.per_PicSave = new HashSet<per_PicSave>();
        }
    
        public long per_P_ID { get; set; }
        public string per_ArchivesID { get; set; }
        public string per_Archival_cat_code { get; set; }
        public string per_AggregationLevel { get; set; }
        public string per_Uniquce_ide { get; set; }
        public string per_Archival_code { get; set; }
        public string per_Title { get; set; }
        public string per_Cameraman { get; set; }
        public string per_DescriptedBy { get; set; }
        public string per_Digitization_aut { get; set; }
        public Nullable<System.DateTime> per_CreationDate { get; set; }
        public Nullable<System.DateTime> per_DigitizationDate { get; set; }
        public Nullable<System.DateTime> per_ModifiedDate { get; set; }
        public string per_Place { get; set; }
        public string per_People { get; set; }
        public string per_Background { get; set; }
        public string per_GPS_version { get; set; }
        public string per_GPS_latitude_ref { get; set; }
        public string per_Latitude { get; set; }
        public string per_GPS_Lon_ref { get; set; }
        public string per_Longitude { get; set; }
        public string per_Altitude_ref { get; set; }
        public string per_Altitude { get; set; }
        public string per_Img_dir_ref { get; set; }
        public string per_Img_dir { get; set; }
        public string per_Acquisition_app { get; set; }
        public string per_ProvenanceName { get; set; }
        public string per_Source_Ide { get; set; }
        public string per_Retention_per { get; set; }
        public string per_Security_cla { get; set; }
        public string per_Control_ide { get; set; }
        public string per_Copyright_inf { get; set; }
        public string per_Annotation { get; set; }
        public string per_Online_loc { get; set; }
        public string per_Offline_loc { get; set; }
        public string per_CreationWay { get; set; }
        public string per_Device_man { get; set; }
        public string per_Device_mod_num { get; set; }
        public string per_Device_sen { get; set; }
        public string per_Software { get; set; }
        public string per_Manage_sys_des { get; set; }
        public string per_Computer_fil_name { get; set; }
        public string per_Computer_fil_size { get; set; }
        public string per_FormatName { get; set; }
        public string per_FormatVersion { get; set; }
        public string per_Format_des { get; set; }
        public string per_X_resolution { get; set; }
        public string per_Y_resolution { get; set; }
        public string per_Image_Height { get; set; }
        public string per_Image_Width { get; set; }
        public string per_Color_Space { get; set; }
        public string per_YCbCr { get; set; }
        public string per_Samples_per_pix { get; set; }
        public string per_Bits_per_sample { get; set; }
        public string per_Image_com_sch { get; set; }
        public string per_Image_com_rat { get; set; }
        public string per_ByteOrder { get; set; }
        public string per_ExifVersion { get; set; }
        public string per_Related_rec_ID { get; set; }
        public string per_Sig_for_dis { get; set; }
        public Nullable<System.DateTime> per_SignatureDate { get; set; }
        public string per_Signer { get; set; }
        public string per_signature { get; set; }
        public string per_Certificate { get; set; }
        public string per_Certificate_ref { get; set; }
        public string per_Signature_alg { get; set; }
        public string per_BusinessType { get; set; }
        public string per_BusinessName { get; set; }
        public Nullable<System.DateTime> per_Bus_beg_date { get; set; }
        public Nullable<System.DateTime> per_Bus_end_date { get; set; }
        public string per_Business_des { get; set; }
        public string per_Action_ide { get; set; }
        public string per_Management_act { get; set; }
        public Nullable<System.DateTime> per_ActionTime { get; set; }
        public string per_Mana_act_des { get; set; }
        public string per_AgentID { get; set; }
        public string per_AgentName { get; set; }
        public string per_AgentType { get; set; }
        public string per_Agent_ide { get; set; }
        public string per_Agent_bel_to { get; set; }
        public string per_Mandate_ide { get; set; }
        public string per_MandateName { get; set; }
        public string per_MandateType { get; set; }
        public Nullable<System.DateTime> per_IssueDate { get; set; }
        public string per_Related_ent_ide { get; set; }
        public string per_Entities_rel_type { get; set; }
        public string per_Entities_rel { get; set; }
    
        public virtual ICollection<per_Box> per_Box { get; set; }
        public virtual ICollection<per_Data> per_Data { get; set; }
        public virtual ICollection<per_PicSave> per_PicSave { get; set; }
    }
}
