//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERMessage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class per_Role
    {
        public per_Role()
        {
            this.per_User = new HashSet<per_User>();
            this.per_RoleRight = new HashSet<per_RoleRight>();
        }
    
        public long Role_ID { get; set; }
        public string Role_Name { get; set; }
        public string Role_Desc { get; set; }
    
        public virtual ICollection<per_User> per_User { get; set; }
        public virtual ICollection<per_RoleRight> per_RoleRight { get; set; }
    }
}
