//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERMessage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PERMessageEntities : DbContext
    {
        public PERMessageEntities()
            : base("name=PERMessageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<per_Borrow> per_Borrow { get; set; }
        public DbSet<per_Box> per_Box { get; set; }
        public DbSet<per_Data> per_Data { get; set; }
        public DbSet<per_InfoData> per_InfoData { get; set; }
        public DbSet<per_Log> per_Log { get; set; }
        public DbSet<per_PicSave> per_PicSave { get; set; }
        public DbSet<per_RightCode> per_RightCode { get; set; }
        public DbSet<per_Role> per_Role { get; set; }
        public DbSet<per_RoleRight> per_RoleRight { get; set; }
        public DbSet<per_User> per_User { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
